data:
  type: all
  base_path: 'data/'
  processed_path: 'processed_all_dialogs_data'
  word_threshold: 6
  max_seq_length: 200
  sentence_diff: 0.33
  testset_size: 50000

  PAD_ID: 0
  UNK_ID: 1
  START_ID: 2
  EOS_ID: 3

model:
  batch_size: 32
  num_layers: 4
  num_units: 512
  embed_dim: 300
  embed_share: true
  cell_type: gru
  dropout: 0.2
  encoder_type: bi
  attention_mechanism: bahdanau

train:
  learning_rate: 0.001
  sampling_probability: 0.4

  train_steps: 100000
  model_dir: 'logs/all_dialogs'

  save_checkpoints_steps: 1000
  loss_hook_n_iter: 1000
  check_hook_n_iter: 1000
  min_eval_frequency: 1000

predict:
  beam_width: 0
  length_penalty_weight: 1.0
