data:
  base_path: 'data/cornell_movie_dialogs_corpus/'
  conversation_fname: 'movie_conversations.txt'
  line_fname: 'movie_lines.txt'
  processed_path: 'processed_cornell_movie_dialogs_data'

  word_threshold: 2
  max_seq_length: 200
  testset_size: 25000
  sentence_diff: 0.33

  PAD_ID: 0
  UNK_ID: 1
  START_ID: 2
  EOS_ID: 3

model:
  batch_size: 32
  num_layers: 3
  num_units: 512
  embed_dim: 256
  embed_share: true
  cell_type: gru
  dropout: 0.2
  encoder_type: bi
  attention_mechanism: normed_bahdanau

train:
  learning_rate: 0.001
  sampling_probability: 0.25

  train_steps: 100000
  model_dir: 'logs/cornell_movie_dialogs'

  save_checkpoints_steps: 1000
  loss_hook_n_iter: 1000
  check_hook_n_iter: 1000
  min_eval_frequency: 1000

  print_verbose: True
  debug: False

predict:
  beam_width: 5
  length_penalty_weight: 1.0

slack:
  webhook_url: ""
