data:
  type: twitter
  base_path: 'data/'
  line_fname: 'twitter_en.txt'
  processed_path: 'processed_twitter_dialogs_data'
  word_threshold: 2
  max_seq_length: 200
  testset_size: 25000

  PAD_ID: 0
  UNK_ID: 1
  START_ID: 2
  EOS_ID: 3

model:
  num_layers: 3
  num_units: 512
  embed_dim: 256
  embed_share: true
  cell_type: gru
  dropout: 0.2
  encoder_type: bi
  attention_mechanism: normed_bahdanau

train:
  batch_size: 32
  learning_rate: 0.001
  train_steps: 100000
  model_dir: 'logs/twitter_dialogs'
  save_every: 1000
  loss_hook_n_iter: 1000
  check_hook_n_iter: 1000
  min_eval_frequency: 1000

predict:
  beam_width: 0
  length_penalty_weight: 1.0
